- name: disable nodejs version
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs 20
  ansible.builtin.command: dnf module enable nodejs:20 -y
  
- name: install nodejs
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - mysql    

- name: create expense user
  ansible.builtin.user:
    name: expense

- name: include from common role
  # tags: 
  #   - deployments
  include_role:
    name: common    
    tasks_from: main 

- name: install dependencies
  tags: 
    - deployments
  community.general.npm:
    path: /app

- name: start backend service
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: install mysql libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
    - cryptography
    - PyMySQL

- name: import mysql schema
  ansible.builtin.mysql_db:
    name: all
    state: import     
    target: /app/schema/backend.sql
    login_user: "{{ MYSQL_USER }}"
    login_password: "{{ MYSQL_PASSWORD }}"
    login_host: "{{ MYSQL_HOST }}"

- name: deamon reload and restart service
  tags: 
    - deployments
  ansible.builtin.systemd_service:
    name: backend
    enabled: true
    state: restarted
    daemon_reload: true